### ISSUE TITLE
CTF Maps Don't automatically download

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-quake2-freeplay#2]
Could be casing issue; eg had to use all caps for `gamemap BHCTF3`

![image](https://user-images.githubusercontent.com/12804982/115973823-82ade080-a51d-11eb-8a45-e83e7f3057fe.png)

**Comment by dudleycodes** [comment]
`2fortgore` seemed to download; so more evidence of a character casing issue 

![image](https://user-images.githubusercontent.com/12804982/115973859-d15b7a80-a51d-11eb-8d5e-dc5c81094846.png)

**Comment by JustinBenedick** [comment]
renamed all map files on fastdl server

**Comment by JustinBenedick** [comment]
![20210428181233_1](https://user-images.githubusercontent.com/1591013/116484423-a723f880-a84e-11eb-8d7f-802b88ce4c45.jpg)

Custom maps and pakfiles are downloading.

**Comment by dudleycodes** [comment]
cool! we'll verify this on the next server bake night - and then close this issue out
